source 'https://rubygems.org'
gem 'openc_bot', git: 'https://github.com/openc/openc_bot.git', :submodules => true
gem 'openc_industry_codes', :git => 'git@github.com:openc/openc_industry_codes.git'
gem 'mechanize'
gem 'awesome_print'
group :test do
  gem 'rspec'
  # gem 'byebug'
end
